/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author Claudio
 */
public class VistaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        panel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnCerrarSesion = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmTareas = new javax.swing.JMenu();
        jmCrearTarea = new javax.swing.JMenuItem();
        jmTareasPendientes = new javax.swing.JMenuItem();
        jmOTs = new javax.swing.JMenuItem();
        jmPlanes = new javax.swing.JMenuItem();
        jmMaq = new javax.swing.JMenu();
        jmMaquinas = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jmCrearSolicitud = new javax.swing.JMenuItem();
        jmVerSolicitudes = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmCategorias = new javax.swing.JMenuItem();
        jmTrabajadores = new javax.swing.JMenuItem();
        jmCerrarSesion = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(6);

        jLabel2.setText("ELIJA UNA DE LAS OPCIONES DEL MENÚ PARA INICIAR");

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(333, Short.MAX_VALUE))
        );

        btnCerrarSesion.setText("Cerrar Sesiòn");

        jLabel1.setText("jLabel1");

        jmTareas.setText("Tareas");

        jmCrearTarea.setText("Crear Tarea");
        jmTareas.add(jmCrearTarea);

        jmTareasPendientes.setText("Tareas Pendientes");
        jmTareasPendientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmTareasPendientesActionPerformed(evt);
            }
        });
        jmTareas.add(jmTareasPendientes);

        jmOTs.setText("Órdenes de Trabajo");
        jmTareas.add(jmOTs);

        jmPlanes.setText("Planes de Tareas");
        jmTareas.add(jmPlanes);

        jMenuBar1.add(jmTareas);

        jmMaq.setText("Máquinas");

        jmMaquinas.setText("Ver Máquinas");
        jmMaquinas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmMaquinasActionPerformed(evt);
            }
        });
        jmMaq.add(jmMaquinas);

        jMenuBar1.add(jmMaq);

        jMenu1.setText("Solicitudes");

        jmCrearSolicitud.setText("Crear y Programar Solicitudes");
        jMenu1.add(jmCrearSolicitud);

        jmVerSolicitudes.setText("Ver Todas");
        jmVerSolicitudes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmVerSolicitudesActionPerformed(evt);
            }
        });
        jMenu1.add(jmVerSolicitudes);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Usuarios");

        jmCategorias.setText("Categorias");
        jmCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCategoriasActionPerformed(evt);
            }
        });
        jMenu2.add(jmCategorias);

        jmTrabajadores.setText("Trabajadores");
        jmTrabajadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmTrabajadoresActionPerformed(evt);
            }
        });
        jMenu2.add(jmTrabajadores);

        jmCerrarSesion.setText("Cerrar Sesión");
        jMenu2.add(jmCerrarSesion);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(416, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(btnCerrarSesion)
                .addContainerGap())
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCerrarSesion)
                    .addComponent(jLabel1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmVerSolicitudesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmVerSolicitudesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmVerSolicitudesActionPerformed

    private void jmTareasPendientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmTareasPendientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmTareasPendientesActionPerformed

    private void jmTrabajadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmTrabajadoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmTrabajadoresActionPerformed

    private void jmMaquinasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmMaquinasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmMaquinasActionPerformed

    private void jmCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCategoriasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmCategoriasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCerrarSesion;
    public javax.swing.JDialog jDialog1;
    public javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JMenu jMenu1;
    public javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JMenuItem jmCategorias;
    public javax.swing.JMenuItem jmCerrarSesion;
    public javax.swing.JMenuItem jmCrearSolicitud;
    public javax.swing.JMenuItem jmCrearTarea;
    public javax.swing.JMenu jmMaq;
    public javax.swing.JMenuItem jmMaquinas;
    public javax.swing.JMenuItem jmOTs;
    public javax.swing.JMenuItem jmPlanes;
    public javax.swing.JMenu jmTareas;
    public javax.swing.JMenuItem jmTareasPendientes;
    public javax.swing.JMenuItem jmTrabajadores;
    public javax.swing.JMenuItem jmVerSolicitudes;
    public javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables
}
